export const PAST_ACCEPTABLE_INCREASE_COLOR = '#8884d8';
export const PAST_MONTHLY_DATA_COLOR = '#191a19';
export const FUTURE_FORECAST_COLOR = '#aafffe';
export const FUTURE_ACCEPTABLE_INCREASE_COLOR = '#191a19';